name: SOC Compliance Report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  soc-compliance:
    runs-on: ubuntu-latest

    env:
      TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      ORG_GITHUB: ${{ secrets.ORG_GITHUB }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run SOC compliance script
        run: python scripts/generate_csv.py

      - name: Upload SOC compliance report artifact
        uses: actions/upload-artifact@v4
        with:
          name: soc_compliant_repos
          path: reports/soc_compliant_repos2.csv
