name: Generate SOC Codacy Report

on:
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to commit changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run SOC Codacy Report Script
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          ORG_GITHUB: ${{ secrets.ORG_GITHUB }}
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
        run: |
          python scripts/generate_csv2.py

      - name: Commit and push Codacy report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          latest_file=$(ls -t reports/codacy_soc_compliant_report_*.csv | head -n 1)

          if [ -z "$latest_file" ]; then
            echo "No Codacy report found to commit."
            exit 0
          fi

          git add "$latest_file"

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update SOC compliant Codacy report [skip ci]" || echo "Nothing to commit"
            git push
          fi

