name: Generate SOC Codacy Report

on:
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed to push changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run SOC Codacy Report Script
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          ORG_GITHUB: ${{ secrets.ORG_GITHUB }}
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
        run: |
          python path/to/your/script.py

      - name: Commit and push report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/soc_compliant_repos2.csv
          git commit -m "Update SOC compliant Codacy report [skip ci]" || echo "No changes to commit"
          git push
